### ISSUE TITLE
Broken libfreenect2 linkage

### ISSUE THREAD

**Issue by Algomorph** [arpg/HAL#140] opened 2017-01-27 17:48 UTC
I'm getting this issue when trying to compile arpg_apps or the Kangaroo example problem (any executable that links to HAL):

```
/usr/local/lib/libfreenect2.so: undefined reference to `clReleaseMemObject@OPENCL_1.0'
/usr/local/lib/libfreenect2.so: undefined reference to `clReleaseCommandQueue@OPENCL_1.0'
/usr/local/lib/libfreenect2.so: undefined reference to `clEnqueueWriteBuffer@OPENCL_1.0'
/usr/local/lib/libfreenect2.so: undefined reference to `clReleaseDevice@OPENCL_1.2'
/usr/local/lib/libfreenect2.so: undefined reference to `clSetKernelArg@OPENCL_1.0'
/usr/local/lib/libfreenect2.so: undefined reference to `clRetainKernel@OPENCL_1.0'
/usr/local/lib/libfreenect2.so: undefined reference to `clCreateContext@OPENCL_1.0'
/usr/local/lib/libfreenect2.so: undefined reference to `clReleaseProgram@OPENCL_1.0'
... (etc)
```

I somehow got the Kangaroo KinectFusion to compile by linking OpenCL to it, but it's not working for the arpg_apps for some reason. Any ideas?

**Comment by crheckman** [comment] 2017-01-29 17:59
Thanks for your report. We've never supported OpenCL explicitly so I don't know what the problem might be, but I would be happy to try and build in some support.

Just to clarify: is the case that you're trying to compile Kangaroo with OpenCL (rather than CUDA which I think is what it relies on currently) and you're getting linking errors for the libfreenect OpenCL methods? Thanks.

**Comment by Algomorph** [comment] 2017-01-30 17:32
@crheckman , Kangaroo KinectFusion app (unsupported) compiles just fine after I link OpenCL to it. No, I'm not trying to use OpenCL instead of CUDA, it just gets linking errors because of the HAL-->libfreenect2-->OpenCL dependency unless I explicitly add finding & linking of the OpenCL in the cmake to the build target.
The real problem is arpg_apps. Those are having the same problem, but the solution that worked for me in the KinectFusion app for whatever reason doesn't seem to be working, i.e. I'm still getting undefined reference error trying to compile either SensorViewer or SensorLogger. At this point, I've just written a short  app that simply reads raw frames from Kinect2 and writes them to disk instead of using HAL logger.

**Comment by crheckman** [comment] 2018-06-22 21:29
Sounds like this problem's addressed at least as it refers to getting raw frames fixed, and the problem is in arpg_apps anyway and not this, so closing for now.

**Closed by crheckman** 2018-06-22 21:29 UTC
